name: Electrum-HMS Builds

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Set tag for release'
        required: true
      release-name:
          description: 'Specify a name for release'
          required: true

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
      - name: Builder image
        env:
          TARGET_OS: Windows
        run: docker build -t electrum-hms-wine-builder-img ./contrib/build-wine/
      - name: Compile Windows binary
        env:
          TARGET_OS: Windows
        run: docker run --name electrum-hms-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum-hms --rm --workdir /opt/wine64/drive_c/electrum-hms/contrib/build-wine electrum-hms-wine-builder-img ./make_win.sh
      - name: Upload Release Windows
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ github.event.inputs.release-name }}
          tag_name: ${{ github.event.inputs.tags }}
          files: |
            /home/runner/work/electrum-hemis/electrum-hemis/contrib/build-wine/dist/electrum-hms-4.5.4-portable.exe
            /home/runner/work/electrum-hemis/electrum-hemis/contrib/build-wine/dist/electrum-hms-4.5.4-setup.exe
            /home/runner/work/electrum-hemis/electrum-hemis/contrib/build-wine/dist/electrum-hms-4.5.4.exe

  appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
      - name: Builder image
        run: docker build -t electrum-hms-appimage-builder-img ./contrib/build-linux/appimage/
      - name: Compile Linux AppImage
        run: docker run --name electrum-hms-appimage-builder-cont -v $PWD:/opt/electrum-hms --rm --workdir /opt/electrum-hms/contrib/build-linux/appimage electrum-hms-appimage-builder-img ./make_appimage.sh
      - name: Upload Release AppImage
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ github.event.inputs.release-name }}
          tag_name: ${{ github.event.inputs.tags }}
          files:
            /home/runner/work/electrum-hemis/electrum-hemis/dist/electrum-hms-4.5.4-x86_64.AppImage
  tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Builder image
        run: docker build -t electrum-hms-sdist-builder-img ./contrib/build-linux/sdist/
      - name: Compile Linux tarball
        run: docker run --name electrum-hms-sdist-builder-cont -v $PWD:/opt/electrum-hms --rm --workdir /opt/electrum-hms/contrib/build-linux/sdist electrum-hms-sdist-builder-img ./make_sdist.sh
      - name: Upload Release Tarball
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ github.event.inputs.release-name }}
          tag_name: ${{ github.event.inputs.tags }}
          files:
            /home/runner/work/electrum-hemis/electrum-hemis/dist/Electrum-hms-4.5.4.tar.gz

  source-only-tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Builder image
        run: docker build -t electrum-hms-source-only-tarball-builder-img ./contrib/build-linux/sdist/
      - name: Compile Linux tarball
        run: docker run --name electrum-hms-source-only-tarball-builder-cont -v $PWD:/opt/electrum-hms --rm --workdir /opt/electrum-hms/contrib/build-linux/sdist --env OMIT_UNCLEAN_FILES=1 electrum-hms-source-only-tarball-builder-img ./make_sdist.sh
      - name: Upload Release Source Only Tarball
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ github.event.inputs.release-name }}
          tag_name: ${{ github.event.inputs.tags }}
          files:
            /home/runner/work/electrum-hemis/electrum-hemis/dist/Electrum-hms-sourceonly-4.5.4.tar.gz

#  android-qml-arm64-v8a:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Free Disk Space (Ubuntu)
#        uses: gruve-p/free-disk-space@main
#        with:
#          # this might remove tools that are actually needed,
#          # if set to "true" but frees about 6 GB
#          tool-cache: true
#
#          # all of these default to true, but feel free to set to
#          # "false" if necessary for your workflow
#          android: true
#          dotnet: true
#          haskell: true
#          docker-images: true
#          codeql-images: true
#          large-packages: true
#          swap-storage: true
#      - name: Builder image
#        run: docker build -t electrum-hms-android-builder-img --file contrib/android/Dockerfile .
#      - name: Compile Android apk
#        env:
#           ENCODED_STRING: ${{ secrets.ANDROID_SIGNING_KEY }}
#        run: |
#          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
#          mkdir "${TMP_KEYSTORE_FILE_PATH}"
#          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/electrumhms.keystore
#          sudo mkdir --parents /.buildozer/.gradle
#          sudo docker run --name electrum-hms-android-builder-cont -v $PWD:/home/user/wspace/electrum-hms -v /.buildozer/.gradle:/home/user/.gradle -v $TMP_KEYSTORE_FILE_PATH:/root/.keystore --workdir /home/user/wspace/electrum-hms electrum-hms-android-builder-img ./contrib/android/make_apk.sh qml arm64-v8a release ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: electrum-hms-${{ github.sha }}-android-arm64-v8a
#          path: dist/*.apk
#          if-no-files-found: error
#          retention-days: 7
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: electrum-hms-${{ github.sha }}-android-arm64-v8a
#
#  android-qml-armeabi-v7a:
#    runs-on: ubuntu-latest 
#    steps:
#      - uses: actions/checkout@v4
#      - name: Free Disk Space (Ubuntu)
#        uses: gruve-p/free-disk-space@main
#        with:
#          # this might remove tools that are actually needed,
#          # if set to "true" but frees about 6 GB
#          tool-cache: true
#
#          # all of these default to true, but feel free to set to
#          # "false" if necessary for your workflow
#          android: true
#          dotnet: true
#          haskell: true
#          docker-images: true
#          codeql-images: true
#          large-packages: true
#          swap-storage: true
#      - name: Builder image
#        run: docker build -t electrum-hms-android-builder-img --file contrib/android/Dockerfile .
#      - name: Compile Android apk
#        env:
#           ENCODED_STRING: ${{ secrets.ANDROID_SIGNING_KEY }}
#        run: |
#          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
#          mkdir "${TMP_KEYSTORE_FILE_PATH}"
#          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/electrumhms.keystore
#          sudo mkdir --parents /.buildozer/.gradle
#          sudo docker run --name electrum-hms-android-builder-cont -v $PWD:/home/user/wspace/electrum-hms -v /.buildozer/.gradle:/home/user/.gradle -v $TMP_KEYSTORE_FILE_PATH:/root/.keystore --workdir /home/user/wspace/electrum-hms electrum-hms-android-builder-img ./contrib/android/make_apk.sh qml armeabi-v7a release ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: electrum-hms-${{ github.sha }}-android-armeabi-v7a
#          path: dist/*.apk
#          if-no-files-found: error
#          retention-days: 7
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: electrum-hms-${{ github.sha }}-android-armeabi-v7a
#
#  android-qml-x86_64:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Free Disk Space (Ubuntu)
#        uses: gruve-p/free-disk-space@main
#        with:
#          # this might remove tools that are actually needed,
#          # if set to "true" but frees about 6 GB
#          tool-cache: true
#
#          # all of these default to true, but feel free to set to
#          # "false" if necessary for your workflow
#          android: true
#          dotnet: true
#          haskell: true
#          docker-images: true
#          codeql-images: true
#          large-packages: true
#          swap-storage: true
#      - name: Builder image
#        run: docker build -t electrum-hms-android-builder-img --file contrib/android/Dockerfile .
#      - name: Compile Android apk
#        env:
#           ENCODED_STRING: ${{ secrets.ANDROID_SIGNING_KEY }}
#        run: |
#          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
#          mkdir "${TMP_KEYSTORE_FILE_PATH}"
#          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/electrumhms.keystore
#          sudo mkdir --parents /.buildozer/.gradle
#          sudo docker run --name electrum-hms-android-builder-cont -v $PWD:/home/user/wspace/electrum-hms -v /.buildozer/.gradle:/home/user/.gradle -v $TMP_KEYSTORE_FILE_PATH:/root/.keystore --workdir /home/user/wspace/electrum-hms electrum-hms-android-builder-img ./contrib/android/make_apk.sh qml x86_64 release ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: electrum-hms-${{ github.sha }}-android-x86_64
#          path: dist/*.apk
#          if-no-files-found: error
#          retention-days: 7
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: electrum-hms-${{ github.sha }}-android-x86_64

  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 12.4.0
      - name: Compile OSX dmg
        run: ./contrib/osx/make_osx.sh
      - name: Upload Release Mac
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: ${{ github.event.inputs.release-name }}
          tag_name: ${{ github.event.inputs.tags }}
          files:
            /Users/runner/work/electrum-hemis/electrum-hemis/dist/electrum-hms-4.5.4-unsigned.dmg